### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zmwangx** [SNH48Live/snh48schedule#1]
- [ ] Download and serve images locally.
- [ ] Possibly expand to more than ten entries.
- [ ] Add a toggle to switch between China Standard Time and the local timezone for datetime display.
- [ ] Include SNH48's tours (in Beijing, Guangzhou and Shenyang).
- [ ] Proper logging.
- [ ] Footer.
